function results = speechRecognizer(sigDir,logDir,db,model,uasrPath,uasrDataPath)
if(nargin<6)
	uasrDataPath = '~/uasr-data/';
end
if(nargin<5)
	uasrPath = '~/uasr/';
end
if(nargin<4)
	model = '3_15';
end

if (strcmp(db,'apollo'))
	script = fullfile(uasrPath,'scripts/dlabpro/JLSS.xtp');
	config = fullfile(uasrDataPath,'apollo/apollo.cfg');
	recogCall = ['dlabpro ' script ' --offline ' ...
		...%'/erk/daten2/uasr-maintenance/uasr-data/apollo/apollo.cfg' ... 
		config ...
		' -Pdir.sig=' sigDir ...
		' -Pdir.log=' logDir ...
		' -Pam.model=' model ...
		' -Pdb=ssmg' ...
		' -Pexp=SAMURAI' ...
		' -Pvoc=' fullfile(uasrDataPath,'apollo/apollo.voc.txt') ...
		' -Psigl=' fullfile(uasrDataPath,'apollo/1020.flst') ...
		' 2>&1'];
	disp(recogCall);
	[status out] = system(recogCall,'-echo');

elseif (strcmp(db,'samurai'))
	script = fullfile(uasrPath,'scripts/dlabpro/HMM.xtp evl');
	config = fullfile(uasrDataPath,'ssmg/common/info/SAMURAI_0.cfg');
	[status out] = system(['dlabpro ' script ' ' ...
						   %' ~/uasr-data/ssmg/common/info/SAMURAI_0.cfg' ...
						   config ...
						   ' -Pam.model=' model ...
						   ' -Pdir.fea=' logDir ...
						   ' -Pdir.sig=' sigDir ...
						   ' -v2'],'-echo'); %...
						   %' -Pflist.test=test.flst'...
						   %' -Pdir.flists=/erk/tmp/feher/twinBfSpeechRecog']);
	%parse and return result
	results = speechRecogGetResults(out,db);
else
	error ([db ' is not a valid corpus name']);
end

%parse and return result
results = speechRecogGetResults(out,db);
