function results = speechRecognizer(sigDir,logDir,db,model)
if(nargin<4)
	model = '3_15';
end
if (strcmp(db,'apollo'))
	[status out] =...
		system(['dlabpro ~/uasr/scripts/dlabpro/JLSS.xtp --offline ' ...
		'/erk/daten2/uasr-maintenance/uasr-data/apollo/apollo.cfg' ... 
		' -Pdir.sig=' sigDir ...
		' -Pdir.log=' logDir ...
		' -Pam.model=' model ...
		' -Pdb=ssmg' ...
		' -Pexp=SAMURAI' ...
		' -Pvoc=/erk/daten2/uasr-maintenance/uasr-data/apollo/apollo.voc.txt'...
		' -Psigl=/erk/daten2/uasr-maintenance/uasr-data/apollo/1020.flst']...
		,'-echo');

elseif (strcmp(db,'samurai'))
	[status out] = system(['dlabpro ~/uasr/scripts/dlabpro/HMM.xtp evl ' ...
						   '~/uasr-data/ssmg/common/info/SAMURAI_0.cfg' ...
						   ' -Pam.model=' model ...
						   ' -Pdir.fea=' logDir ...
						   ' -Pdir.sig=' sigDir ...
						   ' -v2'],'-echo'); %...
						   %' -Pflist.test=test.flst'...
						   %' -Pdir.flists=/erk/tmp/feher/twinBfSpeechRecog']);
	%parse and return result
	results = speechRecogGetResults(out,db);
else
	error ([db ' is not a valid corpus name']);
end

%parse and return result
results = speechRecogGetResults(out,db);
